apiVersion: apps/v1
kind: Deployment
metadata:
  name: timewarp
  labels:
    app: timewarp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timewarp
  template:
    metadata:
      labels:
        app: timewarp
    spec:
      containers:
      - name: timewarp
        image: cordelltech/timewarp
        ports:
        - containerPort: 8000
          name: http
