apiVersion: v1
kind: Service
metadata:
  name: timewarp
  labels:
    app: timewarp
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: timewarp
  type: LoadBalancer